// File: sevensegdec_nexys.v
// Generated by MyHDL 0.11.52
// Date:    Tue Sep 29 14:30:02 2026 UTC


`timescale 1ns/10ps

module sevensegdec_nexys (
    bcd,
    sseg,
    bcdled,
    ssanodes,
    invert
);
// Envelope for running a demo in the Nexys4 DDR board for the Seven segment decoder

input [3:0] bcd;
output [6:0] sseg;
reg [6:0] sseg;
output [3:0] bcdled;
wire [3:0] bcdled;
output [7:0] ssanodes;
wire [7:0] ssanodes;
input invert;

reg [6:0] sevensegdec1_ssegout;


// LUT implementation: based on a decoder table
always @(bcd) begin: sevensegdec1_logic
    case (bcd)
        0: sevensegdec1_ssegout = 126;
        1: sevensegdec1_ssegout = 48;
        2: sevensegdec1_ssegout = 109;
        3: sevensegdec1_ssegout = 121;
        4: sevensegdec1_ssegout = 51;
        5: sevensegdec1_ssegout = 91;
        6: sevensegdec1_ssegout = 95;
        7: sevensegdec1_ssegout = 112;
        8: sevensegdec1_ssegout = 127;
        9: sevensegdec1_ssegout = 123;
        10: sevensegdec1_ssegout = 17;
        11: sevensegdec1_ssegout = 118;
        12: sevensegdec1_ssegout = 62;
        13: sevensegdec1_ssegout = 8;
        14: sevensegdec1_ssegout = 1;
        default: sevensegdec1_ssegout = 64;
    endcase
end

// Inverting process for output
always @(sevensegdec1_ssegout, invert) begin: sevensegdec1_invertproc
    if (invert) begin
        sseg = (~sevensegdec1_ssegout);
    end
    else begin
        sseg = sevensegdec1_ssegout;
    end
end

// Process to fill the LEDs for switches and display anodes

assign bcdled = bcd;
assign ssanodes = 8'hfe;

endmodule
