-- File: sevensegdec_nexys.vhd
-- Generated by MyHDL 0.11.52
-- Date:    Tue Sep 29 14:30:01 2026 UTC


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity sevensegdec_nexys is
    port (
        bcd: in unsigned(3 downto 0);
        sseg: out unsigned(6 downto 0);
        bcdled: out unsigned(3 downto 0);
        ssanodes: out unsigned(7 downto 0);
        invert: in std_logic
    );
end entity sevensegdec_nexys;
-- Envelope for running a demo in the Nexys4 DDR board for the Seven segment decoder

architecture MyHDL of sevensegdec_nexys is



signal sevensegdec1_ssegout: unsigned(6 downto 0);

begin




-- LUT implementation: based on a decoder table
sevensegdec1_logic: process (bcd) is
begin
    case to_integer(bcd) is
        when 0 => sevensegdec1_ssegout <= "1111110";
        when 1 => sevensegdec1_ssegout <= "0110000";
        when 2 => sevensegdec1_ssegout <= "1101101";
        when 3 => sevensegdec1_ssegout <= "1111001";
        when 4 => sevensegdec1_ssegout <= "0110011";
        when 5 => sevensegdec1_ssegout <= "1011011";
        when 6 => sevensegdec1_ssegout <= "1011111";
        when 7 => sevensegdec1_ssegout <= "1110000";
        when 8 => sevensegdec1_ssegout <= "1111111";
        when 9 => sevensegdec1_ssegout <= "1111011";
        when 10 => sevensegdec1_ssegout <= "0010001";
        when 11 => sevensegdec1_ssegout <= "1110110";
        when 12 => sevensegdec1_ssegout <= "0111110";
        when 13 => sevensegdec1_ssegout <= "0001000";
        when 14 => sevensegdec1_ssegout <= "0000001";
        when others => sevensegdec1_ssegout <= "1000000";
    end case;
end process sevensegdec1_logic;

-- Inverting process for output
sevensegdec1_invertproc: process (invert, sevensegdec1_ssegout) is
begin
    if bool(invert) then
        sseg <= (not sevensegdec1_ssegout);
    else
        sseg <= sevensegdec1_ssegout;
    end if;
end process sevensegdec1_invertproc;

-- Process to fill the LEDs for switches and display anodes

bcdled <= bcd;
ssanodes <= to_unsigned(254, 8);

end architecture MyHDL;
